# Generated by Django 3.2.9 on 2021-12-03 06:50

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
