# Generated by Django 3.2.9 on 2021-12-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211208_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags_id',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
